name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run test:backends:local
      - run: npm run test:commands
      - run: npm run build
      - run: npm run build:pkg

  backend-s3-test:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Start LocalStack
        run: |
          pip install localstack awscli-local       # install LocalStack cli and awslocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background

          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out
          echo "Startup complete"
      - run: npm run test:backends:s3

  backend-gcp-test:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:backends:gcp

  backend-azure-test:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:backends:azure

  automerge-dependabot-pr:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - unit-test
      - backend-s3-test
      - backend-gcp-test
      - backend-azure-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor

  install-script-test:
    if: github.ref_name == 'main'
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          bash scripts/install.sh
          terrac --help

  e2e-terraform-test:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node
        with:
          node-version: 18
          cache: npm
      - uses: hashicorp/setup-terraform@v3
      - run: npm ci
      - run: npm run test:e2e:terraform
    needs:
      - backend-s3-test

  e2e-opentofu-test:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node
        with:
          node-version: 18
          cache: npm
      - uses: opentofu/setup-opentofu@v1
      - run: npm ci
      - run: npm run test:e2e:opentofu
    needs:
      - backend-s3-test
