name: main

on:
  pull_request:
    branches:
      - main
    paths:
      - scripts/install.sh
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-script-test:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          shell: bash
          command: bash scripts/install.sh && terrac --help
